### ISSUE TITLE
about pareconv cuda code

### ISSUE THREAD

**Issue by CerrieJ** [yaorz97/PARENet#4]
Hi, thanks for nice work!
I see that you have fully implemented Pareconv acceleration using CUDAC, which is a very impressive job. Now I would like to ask if there is a way for me to run your code on a Chinese-AI-accelerator-card without using this CUDAC implementation and instead use PyTorch's existing operators for training? I tried to remove CUDAExtension related code from the code, but failed.

**Comment by yaorz97** [comment]
We use `pointops`  to search the K-nearest points, which can be replaced by the the function in Open3D that uses CPU only.

**Comment by CerrieJ** [comment]
再请教一下，如何替换成Open3D呢？
